import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Layouts/Navbar";
import Footer from "./components/Layouts/Footer";
import CatNavbar from "./components/Layouts/CatNavbar";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>

        <AuthProvider>
          <Navbar />
        <CatNavbar />
        <Toaster position="top-right" />
        {children}
        <Footer />
        </AuthProvider>
        </body>
    </html>
  );
}
